version: '3'
services:
  core0:
    environment:
      JAVA_OPTS: -server -Xms2g -Xmx2g -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    build: .
    image: radixdlt.azurecr.io/radixdlt/radixdlt-core:develop
    networks:
      - minimal_universe
    ports:
      - "10000:10000/tcp"
      - "20000:20000/tcp"
      - "30000:30000/tcp"
      - "10000:10000/udp"
      - "20000:20000/udp"
  core1:
    environment:
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0
      JAVA_OPTS: -server -Xms2g -Xmx2g -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.rmi.port=9012 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50506,suspend=n,server=y
    build: .
    image: radixdlt.azurecr.io/radixdlt/radixdlt-core:develop
    networks:
      - minimal_universe
networks:
  minimal_universe:
    external:
      name: radix_default