version: '3'
services:
  core0:
    build:
      context: .
      dockerfile: Dockerfile.core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core0
      RADIXDLT_NETWORK_SEEDS_REMOTE: core1,core2
      RADIXDLT_CONSENSUS_FIXED_NODE_COUNT: 3
      RADIXDLT_LOG_LEVEL: debug
      RADIXDLT_UNIVERSE: ${RADIXDLT_UNIVERSE}
      JAVA_OPTS: -server -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStoreType=jks -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    image: radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - three_node_universe
    logging:
      options:
        max-size: "10m"
        max-file: "30"
  core1:
    build:
      context: .
      dockerfile: Dockerfile.core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core1
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0,core2
      RADIXDLT_CONSENSUS_FIXED_NODE_COUNT: 3
      RADIXDLT_LOG_LEVEL: debug
      RADIXDLT_UNIVERSE: ${RADIXDLT_UNIVERSE}
      JAVA_OPTS: -server -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.rmi.port=9012 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50506,suspend=n,server=y
    image: radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - three_node_universe
  core2:
    build:
      context: .
      dockerfile: Dockerfile.core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core2
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0,core1
      RADIXDLT_CONSENSUS_FIXED_NODE_COUNT: 3
      RADIXDLT_LOG_LEVEL: debug
      RADIXDLT_UNIVERSE: ${RADIXDLT_UNIVERSE}
      JAVA_OPTS: -server -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9013 -Dcom.sun.management.jmxremote.rmi.port=9013 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50507,suspend=n,server=y
    image: radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - three_node_universe
  faucet:
    build:
      context: .
      dockerfile: Dockerfile.faucet
    environment:
      FAUCET_TOKEN_RRI: ${RADIXDLT_UNIVERSE_TOKEN}
      FAUCET_IDENTITY_KEY: ${RADIXDLT_UNIVERSE_PRIVKEY}
      RADIX_BOOTSTRAP_TRUSTED_NODE: http://core0:8080
      JAVA_OPTS: -server -XX:+HeapDumpOnOutOfMemoryError -Xms512m -Xmx512m -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/urandom
    image: radixdlt/faucet:develop
    networks:
      - three_node_universe
    logging:
      options:
        max-size: "10m"
        max-file: "30"
networks:
  three_node_universe:
