version: '3'
services:
  core0:
    environment:
      RADIXDLT_NETWORK_SEEDS_REMOTE: core1
      #RADIXDLT_NETWORK_DISCOVERY_URLS: https://sunstone.radixdlt.com:8443/explorer/node-finder
      JAVA_OPTS: -server -Xms2g -Xmx2g -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    build: .
    image: radixdlt.azurecr.io/radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - minimal_universe
    ports:
      - "8080:8080"
      - "9011:9011"
      - "9999:9999"
      - "50505:50505"
      - "10000:10000/tcp"
      - "20000:20000/tcp"
      - "30000:30000/tcp"
      - "10000:10000/udp"
      - "20000:20000/udp"
      - "30000:30000/udp"      
  core1:
    environment:
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0
      #RADIXDLT_NETWORK_DISCOVERY_URLS: https://sunstone.radixdlt.com:8443/explorer/node-finder
      JAVA_OPTS: -server -Xms2g -Xmx2g -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.rmi.port=9012 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50506,suspend=n,server=y
    build: .
    image: radixdlt.azurecr.io/radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - minimal_universe
    ports:
      - "8081:8080"
      - "9012:9012"
      - "50506:50506"
networks:
  minimal_universe:
