version: '3'
services:
  core:
    environment:
      RADIXDLT_NETWORK_SEEDS_REMOTE: core
      RADIXDLT_CONSENSUS_FIXED_NODE_COUNT: 1
      JAVA_OPTS: -server -Xms2g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    build: .
    image: radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - single_node
    ports:
      - "8080:8080"
      - "9011:9011"
      - "9999:9999"
      - "50505:50505"
      - "10000:10000/tcp"
      - "20000:20000/tcp"
      - "30000:30000/tcp"
      - "10000:10000/udp"
      - "20000:20000/udp"
      - "30000:30000/udp"
    logging:
      options:
        max-size: "10m"
        max-file: "30"
networks:
  single_node:
